### ISSUE TITLE
Hello, getting this issue

### ISSUE THREAD

**Issue by holdeMp** [shamhi/MemeFiBot#138]
Traceback (most recent call last):
  File "C:\Users\molot\Desktop\MemeFiBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\molot\Desktop\MemeFiBot\bot\utils\__init__.py", line 9, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

**Comment by afridi315** [comment]
First of all, you must install all the required requirements using `pip install -r requirements.txt` command.

Additionally, make sure you select Create Session before running the Tapper. If this is not the case, create the **sessions** folder in the project's root directory and run the script, then select action/option 1 to make the session. 
_P.S: Ensure you have api_id and api_hash added to the .env file._
