### ISSUE TITLE
Keep showing this issue 

### ISSUE THREAD

**Issue by Sketchify-Dev** [shamhi/MemeFiBot#139]
Traceback (most recent call last):
  File "/home/sketchify/MemeFiBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/sketchify/MemeFiBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/sketchify/MemeFiBot/bot/utils/launcher.py", line 7, in <module>
    from pyrogram import Client
  File "/home/sketchify/.local/lib/python3.9/site-packages/pyrogram/__init__.py", line 39, in <module>
    from .client import Client
  File "/home/sketchify/.local/lib/python3.9/site-packages/pyrogram/client.py", line 52, in <module>
    from pyrogram.storage import FileStorage, MemoryStorage
  File "/home/sketchify/.local/lib/python3.9/site-packages/pyrogram/storage/__init__.py", line 19, in <module>
    from .file_storage import FileStorage
  File "/home/sketchify/.local/lib/python3.9/site-packages/pyrogram/storage/file_storage.py", line 21, in <module>
    import sqlite3
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by afridi315** [comment]
rund this command before running the script; `pip install -r requirements.txt` to install the required library first.

**Comment by Sketchify-Dev** [comment]
All done already

Thanks

Do you know how I can add make the balance run faster and all levels should complete within few mins or seconds

**Comment by afridi315** [comment]
You can do it by increasing your tap level and the booster. If you have the booster and you tap level is better, it damage the boss health very fast and will change your levels faster.

**Comment by afridi315** [comment]
You can do it by increasing your tap level and the booster. If you have the booster and your tap level is better, it damages the boss's health very fast and will change your levels faster.
