### ISSUE TITLE
No Module Named Loguru

### ISSUE THREAD

**Issue by Rylynx53** [shamhi/MemeFiBot#154]
Please Help

```
root@localhost:~/MemeFiBot# python3 main.py
Traceback (most recent call last):
  File "/root/MemeFiBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/MemeFiBot/bot/utils/__init__.py", line 1, in <module>
    from .logger import logger
  File "/root/MemeFiBot/bot/utils/logger.py", line 2, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'
```

**Comment by revo12** [comment]
pip install -r requirements.txt
then install loguru
pip install loguru
then try running
python3 main.py

After I did that I got these errors


TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "C:\Users\kukur\Desktop\еее\MemeFiBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\kukur\Desktop\еее\MemeFiBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\kukur\Desktop\еее\MemeFiBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\kukur\Desktop\еее\MemeFiBot\bot\core\tapper.py", line 8, in <module>
    import aiocfscrape
  File "C:\Users\kukur\venv\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\kukur\venv\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\kukur\venv\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\kukur\venv\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kukur\venv\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\kukur\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kukur\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by nhathoang24** [comment]
> pip install -r requirements.txt then install loguru pip install loguru then try running python3 main.py
> 
> After I did that I got these errors
> 
> TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups Traceback (most recent call last): File "C:\Users\kukur\Desktop\еее\MemeFiBot\main.py", line 4, in from bot.utils.launcher import process File "C:\Users\kukur\Desktop\еее\MemeFiBot\bot\utils__init__.py", line 2, in from . import launcher File "C:\Users\kukur\Desktop\еее\MemeFiBot\bot\utils\launcher.py", line 12, in from bot.core.tapper import run_tapper File "C:\Users\kukur\Desktop\еее\MemeFiBot\bot\core\tapper.py", line 8, in import aiocfscrape File "C:\Users\kukur\venv\Lib\site-packages\aiocfscrape__init__.py", line 8, in import js2py File "C:\Users\kukur\venv\Lib\site-packages\js2py__init__.py", line 72, in from .base import PyJsException File "C:\Users\kukur\venv\Lib\site-packages\js2py\base.py", line 2965, in @js ^^ File "C:\Users\kukur\venv\Lib\site-packages\js2py\base.py", line 165, in Js return PyJsFunction(val, FunctionPrototype) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\kukur\venv\Lib\site-packages\js2py\base.py", line 1377, in **init** cand = fix_js_args(func) ^^^^^^^^^^^^^^^^^ File "C:\Users\kukur\venv\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args code = append_arguments(six.get_function_code(func), ('this', 'arguments')) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\kukur\venv\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments arg = name_translations[inst.arg] ~~~~~~~~~~~~~~~~~^^^^^^^^^^ KeyError: 3

same issue with you

**Comment by TheEmperorGh** [comment]
Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
