### ISSUE TITLE
commit: 311ee99 / js2py error

### ISSUE THREAD

**Issue by zv09** [shamhi/MemeFiBot#157]
python 3.12 + pip3 24.0
ошибка в js2py
Какой ver. python3 рекомендуешь использовать? 

```
Traceback (most recent call last):
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/bot/core/tapper.py", line 8, in <module>
    import aiocfscrape
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/venv/lib/python3.12/site-packages/aiocfscrape/__init__.py", line 8, in <module>
    import js2py
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/venv/lib/python3.12/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/venv/lib/python3.12/site-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/venv/lib/python3.12/site-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/venv/lib/python3.12/site-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XxX/Projects/MemeFi/MemeFiBot_XxX/venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3
```

**Comment by raihante** [comment]
yeah i got this error message too

**Comment by raihante** [comment]
> > yeah i got this error message too
> 
> which version of python are you using and having this bug?

Python 3.12.5 sir

**Comment by zv09** [comment]
seems it is python3.12 issue and need to try 3.10-3.11
not checked by me
