### ISSUE TITLE
Error Sir

### ISSUE THREAD

**Issue by seedev43** [shamhi/MemeFiBot#166]
Traceback (most recent call last):
  File "/home/seedev/public_html/bot-airdrop/MemeFiBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/seedev/public_html/bot-airdrop/MemeFiBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/seedev/public_html/bot-airdrop/MemeFiBot/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/home/seedev/public_html/bot-airdrop/MemeFiBot/bot/core/tapper.py", line 8, in <module>
    import aiocfscrape
  File "/home/seedev/env/lib/python3.12/site-packages/aiocfscrape/__init__.py", line 8, in <module>
    import js2py
  File "/home/seedev/env/lib/python3.12/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/home/seedev/env/lib/python3.12/site-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/home/seedev/env/lib/python3.12/site-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seedev/env/lib/python3.12/site-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/home/seedev/env/lib/python3.12/site-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/seedev/env/lib/python3.12/site-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by mdprana** [comment]
try

pip install --upgrade js2py aiocfscrape

**Comment by Brilliancoder** [comment]
hey bro its still same for ubuntu 24.04 is there any solution?
Traceback (most recent call last):
  File "/home/ubuntu/MemeFiBot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/home/ubuntu/MemeFiBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/home/ubuntu/MemeFiBot/bot/utils/launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "/home/ubuntu/MemeFiBot/bot/core/tapper.py", line 8, in <module>
    import aiocfscrape
  File "/home/ubuntu/MemeFiBot/venv/lib/python3.12/site-packages/aiocfscrape/__init__.py", line 8, in <module>
    import js2py
  File "/home/ubuntu/MemeFiBot/venv/lib/python3.12/site-packages/js2py/__init__.py", line 72, in <module>
    from .base import PyJsException
  File "/home/ubuntu/MemeFiBot/venv/lib/python3.12/site-packages/js2py/base.py", line 2965, in <module>
    @Js
     ^^
  File "/home/ubuntu/MemeFiBot/venv/lib/python3.12/site-packages/js2py/base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/MemeFiBot/venv/lib/python3.12/site-packages/js2py/base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/MemeFiBot/venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/MemeFiBot/venv/lib/python3.12/site-packages/js2py/utils/injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

**Comment by seedev43** [comment]
It doesn't work. I've tried it

Pada Kam, 12 Sep 2024 12.38, Made Pranajaya ***@***.***>
menulis:

**Comment by KeeperSalley** [comment]
try to install python:3.10
