### ISSUE TITLE
Whats problem?

### ISSUE THREAD

**Issue by HollySheeeet** [shamhi/MemeFiBot#200]
After update bot not working

@shamhi pls answer anx fix it.
And add Start.bat

ty.

Wait

**Comment by AlexanderQueen** [comment]
@shamhi

**Comment by HollySheeeet** [comment]
Traceback (most recent call last):
  File "C:\Users\User\MemeFiBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\Users\User\MemeFiBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\Users\User\MemeFiBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\Users\User\MemeFiBot\bot\core\tapper.py", line 8, in <module>
    import aiocfscrape
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\aiocfscrape\__init__.py", line 8, in <module>
    import js2py
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\__init__.py", line 72, in <module>
    from .base import PyJsException
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 2965, in <module>
    @Js
     ^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 165, in Js
    return PyJsFunction(val, FunctionPrototype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\base.py", line 1377, in __init__
    cand = fix_js_args(func)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 27, in fix_js_args
    code = append_arguments(six.get_function_code(func), ('this', 'arguments'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\js2py\utils\injector.py", line 121, in append_arguments
    arg = name_translations[inst.arg]
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 3

I think that the problem is compatibility of python versions, namely, everything indicates that the version should be 3.9 or 3.10, I have the latest version, and there were no such problems before.

Also, these errors occurred after updating and merging changes.

I updated all libraries and JS 2, but the problem did not go away

**Comment by billal7** [comment]
same here. everything stopped working. even trying to add session stuck forever after putting session name

**Comment by HollySheeeet** [comment]
> то же самое здесь. все перестало работать. даже попытка добавить сессию застряла навсегда после ввода имени сеанса

It's very strange, I just downloaded the archive, installed it in another place, reinstalled the libraries, launched it and everything works. Apparently you have some kind of overlays or several different bots and there is a conflict of libraries or something like that. I didn't find another answer, but the method helped me.

**Comment by HollySheeeet** [comment]
It's very strange, I just downloaded the archive, installed it in another place, reinstalled the libraries, launched it and everything works. Apparently you have some kind of overlays or several different bots and there is a conflict of libraries or something like that. I didn't find another answer, but the method helped me.

**Comment by billal7** [comment]
looks like resetting might fix the issue
