### ISSUE TITLE
Ввод API

### ISSUE THREAD

**Issue by Bender-V** [shamhi/MemeFiBot#66]
Как внести данные:
MemeFiBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию

Как правильно прописать API? У меня не получается.

MemeFiBot >>> # API_ID=146678 API_HASH=fhhyff567ghutfhji

не понимает

**Comment by Kit0077** [comment]
> Как внести данные:
> 
> MemeFiBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию
> 
> 
> 
> Как правильно прописать API? У меня не получается.
> 
> 
> 
> MemeFiBot >>> # API_ID=146678 API_HASH=fhhyff567ghutfhji
> 
> 
> 
> не понимает 

В файл .env

**Comment by Bender-V** [comment]
> > Как внести данные:
> > MemeFiBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию
> > Как правильно прописать API? У меня не получается.
> > MemeFiBot >>> # API_ID=146678 API_HASH=fhhyff567ghutfhji
> > не понимает
> 
> В файл .env

Выдает такую ошибку с прокси


(venv) C:\MemeFiBot>python main.py
Traceback (most recent call last):
  File "C:\MemeFiBot\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\MemeFiBot\main.py", line 8, in main
    await process()
  File "C:\MemeFiBot\bot\utils\launcher.py", line 70, in process
    logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies")
                                                                      ^^^^^^^^^^^^^
  File "C:\MemeFiBot\bot\utils\launcher.py", line 39, in get_proxies
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MemeFiBot\bot\utils\launcher.py", line 39, in <listcomp>
    proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MemeFiBot\venv\Lib\site-packages\better_proxy\proxy.py", line 52, in from_str
    raise ValueError(f'Unsupported proxy format: {proxy}')


Какой формат прокси нужен?
в конфигурации забил
type://user:pass@ip:port session1

**Comment by tancyit3** [comment]
> > > Как внести данные:
> > > MemeFiBot >>> # Указываете ваши API_ID и API_HASH, остальное берется по умолчанию
> > > Как правильно прописать API? У меня не получается.
> > > MemeFiBot >>> # API_ID=146678 API_HASH=fhhyff567ghutfhji
> > > не понимает
> > 
> > 
> > В файл .env
> 
> Выдает такую ошибку с прокси
> 
> (venv) C:\MemeFiBot>python main.py Traceback (most recent call last): File "C:\MemeFiBot\main.py", line 13, in asyncio.run(main()) File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run return runner.run(main) ^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run return self._loop.run_until_complete(task) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete return future.result() ^^^^^^^^^^^^^^^ File "C:\MemeFiBot\main.py", line 8, in main await process() File "C:\MemeFiBot\bot\utils\launcher.py", line 70, in process logger.info(f"Detected {len(get_session_names())} sessions | {len(get_proxies())} proxies") ^^^^^^^^^^^^^ File "C:\MemeFiBot\bot\utils\launcher.py", line 39, in get_proxies proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\MemeFiBot\bot\utils\launcher.py", line 39, in proxies = [Proxy.from_str(proxy=row.strip()).as_url for row in file] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\MemeFiBot\venv\Lib\site-packages\better_proxy\proxy.py", line 52, in from_str raise ValueError(f'Unsupported proxy format: {proxy}')
> 
> Какой формат прокси нужен? в конфигурации забил type://user:pass@ip:port session1

IPv4 или IPv4 Shared, лучше вторые, дешевле и так же подходят 
тип socks5

прописываешь в формате
socks5://ip:port@user:pass

**Comment by Bender-V** [comment]
> > Какой формат прокси нужен? в конфигурации забил type://user:pass@ip:port session1
> 
> IPv4 или IPv4 Shared, лучше вторые, дешевле и так же подходят тип socks5
> 
> прописываешь в формате socks5://ip:port@user:pass

А как он поймет к какому аккаунту прокси привязать?
