### ISSUE TITLE
Ошибка прокси

### ISSUE THREAD

**Issue by Bender-V** [shamhi/MemeFiBot#70]
В конфиге включил прокси и забил в файл прокси socks5://ip:port@user:pass
При запуске выдает ошибку:

C:\MemeFiBot>python main.py
Traceback (most recent call last):
  File "C:\MemeFiBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\MemeFiBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\MemeFiBot\bot\utils\launcher.py", line 8, in <module>
    from better_proxy import Proxy
ModuleNotFoundError: No module named 'better_proxy'

**Comment by Freddywhest** [comment]
run `pip install better_proxy`

**Comment by Bender-V** [comment]
> run `pip install better_proxy`

Теперь выдает такую ошибку:

Traceback (most recent call last):
  File "C:\MemeFiBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\MemeFiBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\MemeFiBot\bot\utils\launcher.py", line 10, in <module>
    from bot.config import settings
  File "C:\MemeFiBot\bot\config\__init__.py", line 1, in <module>
    from .config import settings
  File "C:\MemeFiBot\bot\config\config.py", line 1, in <module>
    from pydantic_settings import BaseSettings, SettingsConfigDict
ModuleNotFoundError: No module named 'pydantic_settings'

**Comment by Freddywhest** [comment]
run `pip install -r requirements.txt`
